[package]
name = "the_havel_hakimi_algorithm"
version = "0.1.0"
authors = ["Eduardo <eduardo.gheleno@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
